### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by Vipitis** [pygfx/shadertoy#1]
Tasks for the initial setup of this repository, following https://github.com/pygfx/wgpu-py/issues/452

* [x] duplicate wgpu-py #3 
  * [x] strip everything not Shadertoy related
  * [x] restructure the folders
  * [x] change all imports
  * [x] adapt CI config
* [x] clean up
  * [x] check the source and license of all examples https://github.com/pygfx/shadertoy/pull/10
  * [x] adapt README #13
  * [x] add Code of Conduct ([from pygfx](https://github.com/pygfx/pygfx/blob/main/CODE_OF_CONDUCT.md)) #7 
* [ ] Publish? #16 
  * [x] package name? #9

- [x] PR in wgpu-py to remove the utility, examples and test there https://github.com/pygfx/wgpu-py/pull/455

***
I welcome any help and advice

**Comment by Korijn** [comment]
* Please adopt the code of conduct that was recently added to pygfx as a base, since this repo lives under the same org on github.
* Name: shadertoy-wgpu-py? It's a bit long but it has all the important parts. :)

**Comment by Korijn** [comment]
If you do decide on a name for publishing to pypi, and its available, you may want to publish an early release (even if it's not really viable yet) just to claim the name.

**Comment by Vipitis** [comment]
as for publishing I am not so sure myself. Would it make any sense to set it up as an optional extra for wgpu-py so you end up with something like `pip install wgpu[shadertoy]`

**Comment by almarklein** [comment]
IMO it makes more sense to make `wgpu` a dependency of `shadertoy`, so people can just do `pip install shadertoy`.

**Comment by Vipitis** [comment]
I think we are good for an initial release. Not quite sure what that requires. I setup the github workflow on pypi - do we just need a commit PR with the a tag to trigger the release via CI?

**Comment by Korijn** [comment]
For the initial release to pypi it has to be done manually. Subsequent releases can be done by CI.

You first build a wheel with pip and then publish with twine.
